# Generated by Django 3.0.8 on 2020-07-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20200724_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.Thread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
