# Generated by Django 3.0.8 on 2020-07-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20200724_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='previuos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='threads.Message'),
        ),
    ]
