# Generated by Django 3.0.8 on 2020-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20200724_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='indent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
