# Generated by Django 3.0.8 on 2020-07-30 16:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_message_indent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
