# Generated by Django 3.0.8 on 2020-07-30 16:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_auto_20200730_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='attachment'),
            preserve_default=False,
        ),
    ]
